version: "3"
services:
    app:
        build:
            args:
                user:jkemboe
                uid:1000
            context: ./
            dockerfile: Dockerfile
            image: lola-invoice
            container_name: lola-invoice
            restart: unless-stopped
            working_dir: /var/www
            volumes:
                - ./:/var/www
            networks:
                - lola-invoice

    db:
        image: mysql:5.7
        container_name: lola-invoice
        restart: unless-stopped
        environment:
            MYSQL_DATABASE:
            MYSQL_ROOT_PASSWORD:
            MYSQL_PASSWORD:
            MYSQL_USER:
            SERVICE_TAGS:
            SERVICE_NAME:
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            lola-invoice

    nginx:
        image: nginx:alpine
        container_name: lola-invoice-nginx
        restart: unless-stopped
        ports:
        - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - lola-invoice

    networks:
        lola-invoice:
            driver: bridge
