version: "3.7"
services:

    app:
        build:
            args:
                user: admin
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: lola-invoice
        container_name: lola-invoice
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
        - ./:/var/www
        networks:
        - lola-invoice

    db:
        image: mysql:5.7
        container_name: lola-invoice-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: invoicegen
            MYSQL_ROOT_PASSWORD: commandme007!@~
            MYSQL_PASSWORD: commandme007!@~
            MYSQL_USER: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        # volumes:
        #     - ./docker-compose/mysql:/docker-entrypoint
        networks:
            - lola-invoice

    nginx:
        image: nginx:1.17-alpine
        container_name: lolainvoice-nginx
        restart: unless-stopped
        ports:
        - 8000:80
        volumes:
        - ./:/var/www
        - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
        - lola-invoice

networks:
    lola-invoice:
        driver: bridge
